version: '{build}'
branches:
  only:
  - master
  - appveyor
image: Visual Studio 2019
configuration: Release
build_script:
  - msbuild "C:\projects\wickedengine\WickedEngine.sln" /m /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
platform:
  - x64
  - Win32
  
after_build:
  - cmd: move %APPVEYOR_BUILD_FOLDER%\%PLATFORM%\Release\Editor.exe %APPVEYOR_BUILD_FOLDER%\Editor
  - cmd: 7z a WickedEngineEditor.zip WickedEngine\shaders\ WickedEngine\fonts\ images\ models\ scripts\ shadercompilers\ Documentation\ *.txt *.md Editor\Editor.exe Editor\images\ Editor\sound\ Editor\*.ini Editor\*.ico Editor\*.lua
  - cmd: move %APPVEYOR_BUILD_FOLDER%\%PLATFORM%\Release\Tests.exe %APPVEYOR_BUILD_FOLDER%\Tests
  - cmd: 7z a WickedEngineTests.zip WickedEngine\shaders\ WickedEngine\fonts\ images\ models\ scripts\ shadercompilers\ Documentation\ *.txt *.md Tests\Tests.exe Tests\images\ Tests\sound\ Tests\*.ini Tests\*.ico Tests\*.lua Tests\*.ttf
  
artifacts:
- path: WickedEngineEditor.zip
  name: Editor
- path: WickedEngineTests.zip
  name: Tests

